### ISSUE TITLE
Come faccio ad inserire i treni?

### ISSUE THREAD

**Issue by xzmo212** [guidomichieletto/it-station-boards#1]
ciao, la mia domanda potrebbe essere stupida, ma capendo poco e niente di programmazione, una volta avviato il server php e apache come inserisco i treni? grazie mille

**Comment by guidomichieletto** [comment]
Ciao! Per ora, visto che non è ancora presente una pagina per inserire o modificare i treni, è possibile farlo solamente da database MySQL. Va quindi creato un record nella tabella "treni", uno nella tabella "trenigiorno" che contiene le informazioni del treno che corre in un determinato giorno, e vanno assegnate le fermate al treno nella tabella "trenistazioni". Nel file .sql da importare nel database è già presente un treno con tre fermate (quella che viene visualizzata sui monitor è quella con ID 2), quindi per testare ti consiglierei di usare quello modificando il giorno nella tabella "trenigiorno", mettendo la data odierna, e di modificare l'orario di partenza nella seconda stazione. Per comodità ti ho creato queste query che puoi eseguire per impostare velocemente questi parametri:
`UPDATE trenigiorno SET Giorno = CURDATE() WHERE NumTreno = 4501;`
`UPDATE trenistazioni SET OrarioPrevistoPartenza = ADDTIME(CURRENT_TIMESTAMP(), "00:05:00.000") WHERE NumTreno = 4501 AND IDStazione = 2;`
Il treno viene impostato in partenza 5 minuti dopo l'esecuzione della query.

Quando il treno è in partenza partono anche gli annunci automatici, ma, per questioni di sicurezza dei browser, è necessario premere in un punto a caso della pagina per consentire di riprodurre automaticamente contenuti audio.

**Comment by xzmo212** [comment]
ciao di nuovo, ho provato a inserire già i treni, infatti mi faceva strano che non riuscivo ad impostare i treni... poi ho aperto la console del browser e mi da degli errori.. se riesci a darmi una mano sarebbe grandioso!!

Grazie mille, ti allego un screen degli errori
![errori](https://github.com/guidomichieletto/it-station-boards/assets/24585533/c4959ec4-bf90-41d2-ba57-20d6c0b6a8b4)

**Comment by xzmo212** [comment]
mi sono dimenticato di scriverti, anche disabilitando il cors o avviando la pagina con node.js non funziona.. mi da lo stesso problema...

**Comment by guidomichieletto** [comment]
Ciao, a quanto vedo non hai messo il progetto dentro la cartella "htdocs" di xampp. Questo causa il fatto che il codice PHP non venga eseguito e ritorni errore. Una volta messi i file dentro la cartella, avvia il server apache e prova a recarti dal browser all'indirizzo http://localhost/partenze.html
